name: typed_result
description: A result monad with two subtypes representing a success or a failure
repository: https://github.com/lucastsantos/typed_result
version: 0.0.3

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  matcher: ^0.12.14

dev_dependencies:
  test: any
