name: typed_result
description: A result monad with two subtypes representing a success or a failure
repository: https://github.com/lucastsantos/typed_result
version: 1.0.2

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  matcher: ^0.12.13

dev_dependencies:
  test: any
