name: typed_result
description: A result monad with two subtypes representing a success or a failure
repository: https://github.com/lucastsantos/typed_result
version: 0.0.1

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
